namespace Crap4Net.Tests;

public class CSharpMethodParserTests
{
    private const string File = "/src/App/Sample.cs";

    private static IReadOnlyList<MethodDescriptor> Parse(string source, string path = File) =>
        CSharpMethodParser.Parse(source, path);

    private static List<string> Names(string source) => Parse(source).Select(m => m.Name).ToList();

    [Fact]
    public void Finds_methods_with_their_class_namespace_and_complexity()
    {
        var method = Assert.Single(Parse("""
            namespace App.Services;

            public class Greeter
            {
                public string Greet(string name)
                {
                    if (name is null)
                        return "?";
                    return name;
                }
            }
            """));

        Assert.Equal(new MethodDescriptor("Greet", "Greeter", "App.Services", File, 5, 5, 10, 2), method);
    }

    [Fact]
    public void Location_line_is_the_name_but_the_span_starts_at_the_attributes()
    {
        var method = Assert.Single(Parse("""
            class C
            {
                [HttpGet]
                [Obsolete]
                public void M() { }
            }
            """));

        Assert.Equal((5, 3, 5), (method.Line, method.StartLine, method.EndLine));
    }

    [Fact]
    public void Names_every_kind_of_member_with_a_body()
    {
        var names = Names("""
            class C
            {
                static C() { }
                public C() { }
                ~C() { }
                void M() { }
                int Arrow() => 1;
                public static C operator +(C a, C b) => a;
                public static implicit operator int(C c) => 0;
                int _x;
                int X { get => _x; set { _x = value; } }
                int Y { get; init => _x = value; }
                int Z => _x;
                int this[int i] { get => i; }
                string this[string s] => s;
                event EventHandler E { add { } remove { } }
            }
            """);

        Assert.Equal(
        [
            ".cctor", ".ctor", "Finalize", "M", "Arrow", "operator +", "implicit operator int",
            "X.get", "X.set", "Y.init", "Z.get", "this[].get", "this[].get", "E.add", "E.remove",
        ], names);
    }

    [Fact]
    public void Skips_members_without_a_body()
    {
        var names = Names("""
            abstract class A
            {
                public abstract void Abstract();
                public int Auto { get; set; }
                partial void Hook();
                extern static void Native();
                public A(int x) : base() { }
            }
            interface I
            {
                void Declared();
                void Defaulted() { }
            }
            record R(int Value);
            class Primary(int x) { }
            """);

        Assert.Equal([".ctor", "Defaulted"], names);
    }

    [Fact]
    public void Names_nested_and_generic_types()
    {
        var classes = Parse("""
            class Outer
            {
                class Inner<T, U>
                {
                    void M() { }
                }
                struct S { void N() { } }
            }
            """).Select(m => m.ClassName);

        Assert.Equal(["Outer.Inner<T,U>", "Outer.S"], classes);
    }

    [Fact]
    public void Joins_nested_block_namespaces()
    {
        var method = Assert.Single(Parse("namespace A { namespace B.C { class K { void M() { } } } }"));
        Assert.Equal("A.B.C", method.Namespace);
    }

    [Fact]
    public void Treats_top_level_statements_as_one_member()
    {
        var methods = Parse("""
            using System;

            var x = args.Length;
            if (x > 0)
                Console.WriteLine(Describe(x));

            string Describe(int n) => n > 1 ? "many" : "one";

            class Helper { void M() { } }
            """);

        Assert.Equal(2, methods.Count);
        var topLevel = methods[0];
        Assert.Equal((CSharpMethodParser.TopLevelName, "Program"), (topLevel.Name, topLevel.ClassName));
        Assert.Equal((3, 3, 7), (topLevel.Line, topLevel.StartLine, topLevel.EndLine));
        Assert.Equal(3, topLevel.Complexity);
        Assert.Equal("M", methods[1].Name);
    }

    [Theory]
    [InlineData("// <auto-generated />\nclass C { void M() { } }")]
    [InlineData("// <autogenerated>\n// whatever\n// </autogenerated>\nclass C { void M() { } }")]
    [InlineData("/* <auto-generated> */ class C { void M() { } }")]
    public void Skips_files_with_an_auto_generated_header(string source) =>
        Assert.Empty(Parse(source));

    [Theory]
    [InlineData("/src/App/Thing.g.cs")]
    [InlineData("/src/App/Thing.g.i.cs")]
    [InlineData("/src/App/Form1.Designer.cs")]
    [InlineData("/src/App/Api.generated.cs")]
    public void Skips_generated_file_names(string path) =>
        Assert.Empty(Parse("class C { void M() { } }", path));

    [Fact]
    public void Skips_members_and_types_excluded_from_coverage_or_generated()
    {
        var names = Names("""
            using System.Diagnostics.CodeAnalysis;

            class C
            {
                [ExcludeFromCodeCoverage] void Excluded() { }
                [System.CodeDom.Compiler.GeneratedCodeAttribute("tool", "1")] void Generated() { }
                [ExcludeFromCodeCoverage(Justification = "x")] int P { get => 1; set { } }
                int Q { [ExcludeFromCodeCoverage] get => 1; set { } }
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute] void AliasQualified() { }
                void Kept() { }
            }

            [ExcludeFromCodeCoverage]
            class Hidden
            {
                void M() { }
                class Nested { void N() { } }
            }
            """);

        Assert.Equal(["Q.set", "Kept"], names);
    }

    [Fact]
    public void Skips_ef_core_migration_scaffolding()
    {
        var names = Names("""
            public partial class AddCv : Migration
            {
                protected override void Up(MigrationBuilder b) { }
            }
            partial class AppDbContextModelSnapshot : Microsoft.EntityFrameworkCore.Infrastructure.ModelSnapshot
            {
                protected override void BuildModel(ModelBuilder m) { }
            }
            class MigrationRunner { void Run() { } }
            class Typed : Migration<int> { void Generic() { } }
            class Rooted : global::Migration { void Alias() { } }
            """);

        Assert.Equal(["Run"], names);
    }

    [Fact]
    public void Parses_the_newest_syntax()
    {
        var names = Names("""
            static class Extensions
            {
                extension(string s)
                {
                    public bool IsBlank() => string.IsNullOrWhiteSpace(s);
                }
            }
            class C { public int P { get => field; set => field = value ?? 0; } }
            """);

        Assert.Equal(["IsBlank", "P.get", "P.set"], names);
        Assert.Equal("Extensions", Parse("static class Extensions { extension(int i) { public int Twice() => i * 2; } }")[0].ClassName);
    }
}
